In [52]:
import pandas as pd
import numpy as np

df = pd.read_csv('ecommerce_sales.csv')

In [52]:
import pandas as pd
import numpy as np

df = pd.read_csv('ecommerce_sales.csv')

In [53]:
df.head()

,order_id,order_date,customer_id,customer_age,gender,city,state,customer_segment,customer_type,acquisition_channel,...,shipping_cost,profit,profit_margin,payment_method,shipping_type,delivery_days,order_status,return_reason,customer_rating,support_tickets
0,ORD100000,2024-03-06,CUST00391,45.0,Male,Bengaluru,Karnataka,Consumer,New,Paid Search,...,220.31,562.47,0.3108,Net Banking,Standard,7.0,Delivered,NaN,5.0,1.0
1,ORD100001,2025-07-18,CUST02608,52.0,Male,Mumbai,Maharashtra,Corporate,Existing,Social Media,...,57.63,187.65,0.1026,UPI,Standard,NaN,Cancelled,NaN,NaN,0.0
2,ORD100002,2025-04-22,CUST02963,40.0,Male,Bengaluru,Karnataka,Consumer,Existing,Marketplace,...,103.90,227.12,0.1831,Wallet,Standard,1.0,Delivered,NaN,4.0,2.0
3,ORD100003,2024-11-16,CUST03808,25.0,Female,Ahmedabad,Gujarat,Consumer,Existing,Organic Search,...,122.41,276.75,0.2603,Net Banking,Standard,7.0,Delivered,NaN,4.0,0.0
4,ORD100004,2024-11-12,CUST02975,60.0,Male,Delhi,Delhi,Consumer,Existing,Organic Search,...,163.77,441.92,0.3199,Wallet,Standard,8.0,Delivered,NaN,5.0,1.0

In [54]:
df[df.duplicated(keep=False)].sort_values('customer_id')

,order_id,order_date,customer_id,customer_age,gender,city,state,customer_segment,customer_type,acquisition_channel,...,shipping_cost,profit,profit_margin,payment_method,shipping_type,delivery_days,order_status,return_reason,customer_rating,support_tickets
149,ORD100149,2024-02-12,CUST00046,54.0,Male,Nagpur,Maharashtra,Consumer,New,Email,...,74.00,351.76,0.2165,COD,Standard,2.0,Delivered,NaN,4.0,0.0
15066,ORD100149,2024-02-12,CUST00046,54.0,Male,Nagpur,Maharashtra,Consumer,New,Email,...,74.00,351.76,0.2165,COD,Standard,2.0,Delivered,NaN,4.0,0.0
12888,ORD112888,2025-09-14,CUST00077,29.0,Male,Pune,Maharashtra,Consumer,New,Marketplace,...,61.91,1188.43,0.2852,Wallet,Standard,8.0,Delivered,NaN,5.0,1.0
15080,ORD112888,2025-09-14,CUST00077,29.0,Male,Pune,Maharashtra,Consumer,New,Marketplace,...,61.91,1188.43,0.2852,Wallet,Standard,8.0,Delivered,NaN,5.0,1.0
14329,ORD114329,2025-11-11,CUST00081,57.0,Female,Pune,Maharashtra,Consumer,New,Marketplace,...,291.33,50.79,0.0347,Debit Card,Express,NaN,Pending,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15090,ORD106368,2024-01-20,CUST04968,24.0,Female,Hyderabad,Telangana,Consumer,Existing,Marketplace,...,125.29,157.37,0.2158,Wallet,Standard,NaN,Cancelled,NaN,NaN,0.0
15093,ORD108202,2025-03-06,CUST05100,56.0,Male,Pune,Maharashtra,Consumer,Existing,Organic Search,...,83.66,262.82,0.1051,COD,Standard,7.0,Delivered,NaN,4.0,0.0
8202,ORD108202,2025-03-06,CUST05100,56.0,Male,Pune,Maharashtra,Consumer,Existing,Organic Search,...,83.66,262.82,0.1051,COD,Standard,7.0,Delivered,NaN,4.0,0.0
15071,ORD109857,2025-06-07,CUST05188,45.0,Female,Hyderabad,Telangana,Consumer,Existing,Affiliate,...,225.55,-155.02,-0.3125,Wallet,Standard,NaN,Cancelled,NaN,NaN,0.0
9857,ORD109857,2025-06-07,CUST05188,45.0,Female,Hyderabad,Telangana,Consumer,Existing,Affiliate,...,225.55,-155.02,-0.3125,Wallet,Standard,NaN,Cancelled,NaN,NaN,0.0

In [56]:
df = df.drop_duplicates()

In [57]:
df[df.duplicated(keep=False)].sort_values('customer_id')

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_age, gender, city, state, customer_segment, customer_type, acquisition_channel, product_category, product, quantity, unit_price, discount_pct, discount_amount, coupon_code, gross_sales, revenue, cost, shipping_cost, profit, profit_margin, payment_method, shipping_type, delivery_days, order_status, return_reason, customer_rating, support_tickets]
Index: []

[0 rows x 30 columns]

In [64]:
df['city'].unique()

<StringArray>
['Bengaluru',    'Mumbai', 'Ahmedabad',     'Delhi',      'Pune',     'Surat',
 'Hyderabad',    'Jaipur',   'Lucknow',   'Chennai',   'Kolkata',    'Nagpur']
Length: 12, dtype: str

In [59]:
df['city'] = df['city'].replace(['Mumbai ','mumbai','MUMBAI'],'Mumbai')

In [60]:
df['city'] = df['city'].replace(['Bangalore','bengaluru ','BENGALURU'],'Bengaluru')

In [61]:
df['city'] = df['city'].replace(['PUNE ','pune'],'Pune')

In [62]:
df['city'] = df['city'].replace(['delhi','DELHI ','New Delhi'],'Delhi')

In [70]:
df[df['gender']=='Other']

,order_id,order_date,customer_id,customer_age,gender,city,state,customer_segment,customer_type,acquisition_channel,...,shipping_cost,profit,profit_margin,payment_method,shipping_type,delivery_days,order_status,return_reason,customer_rating,support_tickets
38,ORD100038,2024-07-21,CUST03234,21.0,Other,Hyderabad,Telangana,Corporate,Existing,Paid Search,...,363.92,398.78,0.1630,Net Banking,Same Day,NaN,Failed,NaN,NaN,0.0
78,ORD100078,2025-02-16,CUST01046,23.0,Other,Chennai,Tamil Nadu,Small Business,Existing,Affiliate,...,107.59,8.02,0.0100,Debit Card,Standard,8.0,Delivered,NaN,4.0,1.0
146,ORD100146,2024-01-26,CUST01117,53.0,Other,Surat,Gujarat,Consumer,Existing,Direct,...,144.30,30.85,0.0677,Net Banking,Standard,2.0,Delivered,NaN,2.0,0.0
205,ORD100205,2024-07-13,CUST02666,60.0,Other,Chennai,Tamil Nadu,Corporate,Existing,Direct,...,164.53,4606.12,0.4102,UPI,Standard,3.0,Delivered,NaN,5.0,3.0
246,ORD100246,2025-07-06,CUST03524,23.0,Other,Ahmedabad,Gujarat,Consumer,Existing,Social Media,...,140.12,1152.63,0.2417,Debit Card,Standard,6.0,Delivered,NaN,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14837,ORD114837,2024-12-02,CUST04252,47.0,Other,Delhi,Delhi,Consumer,Existing,Direct,...,66.41,21183.41,0.1868,UPI,Standard,8.0,Delivered,NaN,4.0,2.0
14847,ORD114847,2024-12-28,CUST01240,23.0,Other,Bengaluru,Karnataka,Consumer,Existing,Affiliate,...,188.40,1831.04,0.3966,Credit Card,Standard,4.0,Delivered,NaN,4.0,1.0
14868,ORD114868,2025-10-04,CUST03173,59.0,Other,Lucknow,NaN,Consumer,Existing,Organic Search,...,171.72,1638.01,0.3203,Net Banking,Standard,3.0,Delivered,NaN,5.0,0.0
14932,ORD114932,2025-05-12,CUST05082,21.0,Other,Jaipur,Rajasthan,Consumer,Existing,Email,...,389.23,4635.04,0.2130,EMI,Same Day,NaN,Cancelled,NaN,NaN,1.0
15079,ORD107963,2024-11-17,CUST03245,52.0,Other,Pune,Maharashtra,Consumer,Existing,Social Media,...,110.71,1103.72,0.2008,Wallet,Standard,2.0,Delivered,NaN,4.0,0.0

In [74]:
df.groupby('gender')['customer_age'].mean()

gender
Female    40.956233
Male      41.199057
Name: customer_age, dtype: float64

In [66]:
dfcopy = df.copy()

In [73]:
df['gender'] = df['gender'].replace('Other','Female')

In [79]:
df[df['gender'].isna()]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_age, gender, city, state, customer_segment, customer_type, acquisition_channel, product_category, product, quantity, unit_price, discount_pct, discount_amount, coupon_code, gross_sales, revenue, cost, shipping_cost, profit, profit_margin, payment_method, shipping_type, delivery_days, order_status, return_reason, customer_rating, support_tickets]
Index: []

[0 rows x 30 columns]

In [78]:
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [97]:
df[df['customer_age'].isna()]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_age, gender, city, state, customer_segment, customer_type, acquisition_channel, product_category, product, quantity, unit_price, discount_pct, discount_amount, coupon_code, gross_sales, revenue, cost, shipping_cost, profit, profit_margin, payment_method, shipping_type, delivery_days, order_status, return_reason, customer_rating, support_tickets]
Index: []

[0 rows x 30 columns]

In [95]:
df['customer_age'].median()

np.float64(41.0)

In [98]:
df['customer_age'] = df['customer_age'].fillna(df['customer_age'].median())

In [108]:
df[df['coupon_code'].isna()]

,order_id,order_date,customer_id,customer_age,gender,city,state,customer_segment,customer_type,acquisition_channel,product_category,product,quantity,unit_price,discount_pct,discount_amount,coupon_code,gross_sales,revenue,cost,shipping_cost,profit,profit_margin,payment_method,shipping_type,delivery_days,order_status,return_reason,customer_rating,support_tickets
20,ORD100020,2024-12-31,CUST00674,57.0,Female,Jaipur,Rajasthan,Small Business,New,Affiliate,Fashion,Backpack,3,1698.99,0.00,0.00,NaN,5096.97,5096.97,2908.24,120.37,2068.35,0.4058,UPI,Standard,1.0,Delivered,NaN,5.0,2.0
68,ORD100068,2024-02-25,CUST01338,26.0,Female,Mumbai,Maharashtra,Consumer,Existing,Organic Search,Home & Kitchen,Mixer Grinder,1,4492.89,0.05,224.64,NaN,4492.89,4268.25,2964.05,98.15,1206.04,0.2826,COD,Standard,NaN,Returned,Size/Fit,NaN,0.0
71,ORD100071,2024-05-18,CUST05000,43.0,Male,Lucknow,Uttar Pradesh,Small Business,Existing,Organic Search,Beauty,Face Wash,3,442.54,0.15,199.14,NaN,1327.62,1128.48,851.01,248.31,29.15,0.0258,Debit Card,Express,NaN,Pending,NaN,NaN,1.0
76,ORD100076,2024-08-29,CUST00558,47.0,Female,Delhi,Delhi,Consumer,New,Organic Search,Sports & Fitness,Resistance Bands,2,871.66,0.10,174.33,NaN,1743.32,1568.99,1007.93,235.84,325.21,0.2073,UPI,Express,NaN,Cancelled,NaN,NaN,0.0
92,ORD100092,2025-09-06,CUST02453,19.0,Male,Pune,Maharashtra,Corporate,Existing,Organic Search,Electronics,Smartwatch,4,5338.64,0.00,0.00,NaN,21354.56,21354.56,18603.73,148.28,2602.55,0.1219,Debit Card,Standard,4.0,Delivered,NaN,5.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14987,ORD114987,2024-03-19,CUST01804,19.0,Male,Hyderabad,Telangana,Corporate,Existing,Email,Fashion,Jeans,2,1625.28,0.05,162.53,NaN,3250.56,3088.03,1923.82,138.46,1025.76,0.3322,COD,Express,2.0,Delivered,NaN,5.0,1.0
14999,ORD114999,2024-01-18,CUST04456,49.0,Male,Pune,Maharashtra,Consumer,Existing,Organic Search,Home & Kitchen,Cookware Set,1,3263.97,0.20,652.79,NaN,3263.97,2611.18,2255.94,117.29,237.95,0.0911,Credit Card,Standard,NaN,Delivered,NaN,5.0,0.0
15000,ORD100404,2024-12-30,CUST05152,22.0,Female,Delhi,Delhi,Consumer,Existing,Affiliate,Grocery,Rice,2,821.73,0.00,0.00,NaN,1643.46,1643.46,1347.51,119.90,176.05,0.1071,Wallet,Standard,NaN,Returned,Wrong Item,NaN,1.0
15053,ORD110750,2025-01-15,CUST02012,38.0,Male,Mumbai,Maharashtra,Consumer,Existing,Social Media,Fashion,Backpack,1,1556.38,0.20,311.28,NaN,1556.38,1245.10,834.87,97.11,313.12,0.2515,UPI,Express,1.0,Delivered,NaN,4.0,0.0
15109,ORD100997,2024-09-20,CUST01208,22.0,Female,Bengaluru,Karnataka,Corporate,Existing,Social Media,Grocery,Cereal,4,488.81,0.10,195.52,NaN,1955.24,1759.72,1310.99,163.92,284.80,0.1618,Credit Card,Standard,NaN,Delivered,NaN,4.0,1.0

In [104]:
pd.set_option('display.max_columns', None)

In [113]:
df['coupon_code'] = df['coupon_code'].replace(['nan','NONE'],'No Coupon')
df['coupon_code'] = df['coupon_code'].fillna('No Coupon')

In [114]:
df['coupon_code'].unique()

<StringArray>
['No Coupon', 'SAVE15', 'WELCOME10', 'FESTIVE20', 'BANK10', 'APP5']
Length: 6, dtype: str

In [117]:
df['payment_method'].unique()

<StringArray>
[     'Net Banking',              'UPI',           'Wallet',
      'Credit Card', 'Cash on Delivery',       'Debit Card',
              'EMI',                nan]
Length: 8, dtype: str

In [118]:
df['payment_method'] = df['payment_method'].replace({
    'credit_card' : 'Credit Card',
    'upi' : 'UPI',
    'netbanking' : 'Net Banking',
    'Debit card' : 'Debit Card',
    'COD' : 'Cash on Delivery'
})

In [131]:
df['payment_method'] = df['payment_method'].fillna(df['payment_method'].mode()[0])

In [129]:
df['payment_method'].isna().sum()

np.int64(120)

In [132]:
df['payment_method'].unique()

<StringArray>
[     'Net Banking',              'UPI',           'Wallet',
      'Credit Card', 'Cash on Delivery',       'Debit Card',
              'EMI']
Length: 7, dtype: str

In [136]:
df['delivery_days']

0        7.0
1        NaN
2        1.0
3        7.0
4        8.0
        ...
15102    6.0
15105    7.0
15109    NaN
15114    4.0
15117    NaN
Name: delivery_days, Length: 15030, dtype: float64

In [137]:
df['delivery_days'] = df['delivery_days'].fillna(df.groupby('city')['delivery_days'].transform('mean'))

In [140]:
df['delivery_days'].isna().sum()

np.int64(0)

In [146]:
df[df['return_reason'].notna()]

,order_id,order_date,customer_id,customer_age,gender,city,state,customer_segment,customer_type,acquisition_channel,product_category,product,quantity,unit_price,discount_pct,discount_amount,coupon_code,gross_sales,revenue,cost,shipping_cost,profit,profit_margin,payment_method,shipping_type,delivery_days,order_status,return_reason,customer_rating,support_tickets
6,ORD100006,2024-03-03,CUST01908,36.0,Female,Bengaluru,Karnataka,Consumer,Existing,Organic Search,Fashion,Jacket,1,3123.29,0.10,312.33,No Coupon,3123.29,2810.96,2296.04,123.94,390.99,0.1391,Credit Card,Standard,4.258941,Returned,Wrong Item,NaN,0.0
23,ORD100023,2025-11-07,CUST02835,40.0,Female,Chennai,Tamil Nadu,Consumer,Existing,Marketplace,Electronics,Smartphone,1,33044.98,0.05,1652.25,No Coupon,33044.98,31392.73,21550.23,161.28,9681.22,0.3084,Debit Card,Standard,4.345098,Returned,Quality Issue,NaN,1.0
29,ORD100029,2024-11-19,CUST03725,43.0,Female,Chennai,Tamil Nadu,Consumer,Existing,Direct,Electronics,Smartwatch,1,5279.49,0.00,0.00,No Coupon,5279.49,5279.49,4065.19,239.36,974.94,0.1847,EMI,Standard,4.345098,Returned,Changed Mind,NaN,0.0
36,ORD100036,2025-09-18,CUST04736,41.0,Female,Lucknow,Uttar Pradesh,Consumer,Existing,Organic Search,Fashion,Backpack,4,1227.51,0.25,1227.51,WELCOME10,4910.04,3682.53,2245.94,397.69,1038.90,0.2821,UPI,Same Day,4.614260,Returned,Late Delivery,NaN,0.0
48,ORD100048,2025-05-09,CUST01520,49.0,Male,Chennai,Tamil Nadu,Corporate,Existing,Organic Search,Sports & Fitness,Running Shoes,3,3225.29,0.20,1935.17,No Coupon,9675.87,7740.70,5397.24,163.01,2180.45,0.2817,Credit Card,Standard,4.345098,Returned,Damaged,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14979,ORD114979,2024-01-16,CUST04409,55.0,Female,Mumbai,Maharashtra,Consumer,Existing,Paid Search,Electronics,Smartphone,1,31987.28,0.10,3198.73,No Coupon,31987.28,28788.55,23010.18,172.01,5606.36,0.1947,Wallet,Standard,4.485079,Returned,Late Delivery,NaN,2.0
14982,ORD114982,2024-11-21,CUST00085,59.0,Male,Pune,Maharashtra,Consumer,New,Social Media,Home & Kitchen,Air Fryer,1,7763.43,0.05,388.17,No Coupon,7763.43,7375.26,4709.80,62.79,2602.67,0.3529,Wallet,Express,4.494929,Returned,Late Delivery,NaN,0.0
15000,ORD100404,2024-12-30,CUST05152,22.0,Female,Delhi,Delhi,Consumer,Existing,Affiliate,Grocery,Rice,2,821.73,0.00,0.00,No Coupon,1643.46,1643.46,1347.51,119.90,176.05,0.1071,Wallet,Standard,4.420231,Returned,Wrong Item,NaN,1.0
15020,ORD111240,2025-04-06,CUST03822,47.0,Female,Delhi,Delhi,Consumer,Existing,Organic Search,Grocery,Olive Oil,3,806.88,0.00,0.00,No Coupon,2420.64,2420.64,1584.87,245.78,589.99,0.2437,Credit Card,Standard,4.420231,Returned,Wrong Item,NaN,1.0
15117,ORD107462,2024-06-03,CUST01627,61.0,Female,Delhi,Delhi,Consumer,Existing,Social Media,Beauty,Perfume,1,1437.30,0.15,215.60,WELCOME10,1437.30,1221.70,981.71,221.28,18.71,0.0153,UPI,Standard,4.420231,Returned,Changed Mind,NaN,1.0

In [148]:
df['order_status'].value_counts(dropna=False)

order_status
Delivered    11689
Cancelled     1181
Returned      1064
Pending        606
Failed         490
Name: count, dtype: int64

In [149]:
pd.crosstab(df['order_status'], df['return_reason'], dropna=False)

return_reason,Changed Mind,Damaged,Late Delivery,Quality Issue,Size/Fit,Wrong Item,NaN
order_status,,,,,,,
Cancelled,0,0,0,0,0,0,1181
Delivered,0,0,0,0,0,0,11689
Failed,0,0,0,0,0,0,490
Pending,0,0,0,0,0,0,606
Returned,183,198,174,166,163,180,0

In [150]:
df['return_reason'] = df['return_reason'].fillna('Not Returned')

In [151]:
df['return_reason'].isna().sum()

np.int64(0)

In [152]:
df.info()

<class 'pandas.DataFrame'>
Index: 15030 entries, 0 to 15117
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             15030 non-null  str
 1   order_date           15030 non-null  str
 2   customer_id          15030 non-null  str
 3   customer_age         15030 non-null  float64
 4   gender               15030 non-null  str
 5   city                 15030 non-null  str
 6   state                14879 non-null  str
 7   customer_segment     15030 non-null  str
 8   customer_type        15030 non-null  str
 9   acquisition_channel  15030 non-null  str
 10  product_category     15030 non-null  str
 11  product              15030 non-null  str
 12  quantity             15030 non-null  int64
 13  unit_price           15030 non-null  float64
 14  discount_pct         15030 non-null  float64
 15  discount_amount      15030 non-null  float64
 16  coupon_code          15030 non-null  str
 17  gross_sales          15030 non-null  float64
 18  revenue              15030 non-null  float64
 19  cost                 15030 non-null  float64
 20  shipping_cost        15030 non-null  float64
 21  profit               15030 non-null  float64
 22  profit_margin        15030 non-null  float64
 23  payment_method       15030 non-null  str
 24  shipping_type        15030 non-null  str
 25  delivery_days        15030 non-null  float64
 26  order_status         15030 non-null  str
 27  return_reason        15030 non-null  str
 28  customer_rating      11223 non-null  float64
 29  support_tickets      15030 non-null  float64
dtypes: float64(13), int64(1), str(16)
memory usage: 3.6 MB

In [153]:
df['customer_rating'].isna().sum()

np.int64(3807)

In [155]:
pd.crosstab(df['order_status'], df['customer_rating'], dropna=False)

customer_rating  1.0  2.0   3.0   4.0   5.0   NaN
order_status
Cancelled          0    0     0     0     0  1181
Delivered        414  919  1885  3843  4162   466
Failed             0    0     0     0     0   490
Pending            0    0     0     0     0   606
Returned           0    0     0     0     0  1064

In [156]:
df.groupby('city')['state'].nunique().sort_values(ascending=False).head(10)

city
Ahmedabad    1
Bengaluru    1
Chennai      1
Delhi        1
Hyderabad    1
Jaipur       1
Kolkata      1
Lucknow      1
Mumbai       1
Nagpur       1
Name: state, dtype: int64

In [168]:
city_state = {
    'Mumbai': 'Maharashtra',
    'Pune': 'Maharashtra',
    'Nagpur' : 'Maharashtra',
    'Bengaluru': 'Karnataka',
    'Hyderabad': 'Telangana',
    'Chennai': 'Tamil Nadu',
    'Delhi': 'Delhi',
    'Kolkata': 'West Bengal',
    'Lucknow' : 'Uttar Pradesh',
    'Jaipur' : 'Rajasthan',
    'Ahmedabad' : 'Gujarat',
    'Surat' : 'Gujarat'

}

df['state'] = df['state'].fillna(df['city'].map(city_state))

In [169]:
df[df['state'].isna()]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_age, gender, city, state, customer_segment, customer_type, acquisition_channel, product_category, product, quantity, unit_price, discount_pct, discount_amount, coupon_code, gross_sales, revenue, cost, shipping_cost, profit, profit_margin, payment_method, shipping_type, delivery_days, order_status, return_reason, customer_rating, support_tickets]
Index: []

In [175]:
df.info()

<class 'pandas.DataFrame'>
Index: 15030 entries, 0 to 15117
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             15030 non-null  str
 1   order_date           15030 non-null  str
 2   customer_id          15030 non-null  str
 3   customer_age         15030 non-null  float64
 4   gender               15030 non-null  str
 5   city                 15030 non-null  str
 6   state                15030 non-null  str
 7   customer_segment     15030 non-null  str
 8   customer_type        15030 non-null  str
 9   acquisition_channel  15030 non-null  str
 10  product_category     15030 non-null  str
 11  product              15030 non-null  str
 12  quantity             15030 non-null  int64
 13  unit_price           15030 non-null  float64
 14  discount_pct         15030 non-null  float64
 15  discount_amount      15030 non-null  float64
 16  coupon_code          15030 non-null  str
 17  gross_sales          15030 non-null  float64
 18  revenue              15030 non-null  float64
 19  cost                 15030 non-null  float64
 20  shipping_cost        15030 non-null  float64
 21  profit               15030 non-null  float64
 22  profit_margin        15030 non-null  float64
 23  payment_method       15030 non-null  str
 24  shipping_type        15030 non-null  str
 25  delivery_days        15030 non-null  float64
 26  order_status         15030 non-null  str
 27  return_reason        15030 non-null  str
 28  customer_rating      11223 non-null  float64
 29  support_tickets      15030 non-null  float64
dtypes: float64(13), int64(1), str(16)
memory usage: 3.6 MB

In [201]:
for col in ['customer_age', 'gender',
       'city', 'state', 'customer_segment', 'customer_type',
       'acquisition_channel', 'product_category', 'product', 'quantity',
       'unit_price', 'discount_pct', 'discount_amount', 'coupon_code',
       'gross_sales', 'revenue', 'cost', 'shipping_cost', 'profit',
       'profit_margin', 'payment_method', 'shipping_type', 'delivery_days',
       'order_status', 'return_reason', 'customer_rating', 'support_tickets']:
    print(f"\n{col}:")
    print(df[col].unique())

customer_age:
[45. 52. 40. 25. 60. 57. 36. 46. 47. 32. 50. 22. 18. 44. 59. 37. 31. 51.
 39. 48. 43. 58. 29. 49. 41. 21. 38. 62. 24. 55. 26. 54. 53. 64. 23. 42.
 19. 28. 30. 56. 61. 33. 35. 63. 27. 34. 20.]

gender:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

city:
<StringArray>
['Bengaluru',    'Mumbai', 'Ahmedabad',     'Delhi',      'Pune',     'Surat',
 'Hyderabad',    'Jaipur',   'Lucknow',   'Chennai',   'Kolkata',    'Nagpur']
Length: 12, dtype: str

state:
<StringArray>
[    'Karnataka',   'Maharashtra',       'Gujarat',         'Delhi',
     'Telangana',     'Rajasthan', 'Uttar Pradesh',    'Tamil Nadu',
   'West Bengal']
Length: 9, dtype: str

customer_segment:
<StringArray>
['Consumer', 'Corporate', 'Small Business']
Length: 3, dtype: str

customer_type:
<StringArray>
['New', 'Existing']
Length: 2, dtype: str

acquisition_channel:
<StringArray>
[   'Paid Search',   'Social Media',    'Marketplace', 'Organic Search',
      'Affiliate',         'Direct',          'Email']
Length: 7, dtype: str

product_category:
<StringArray>
['Sports & Fitness',          'Grocery',            'Books',
           'Beauty',          'Fashion',   'Home & Kitchen',
      'Electronics',             'Toys']
Length: 8, dtype: str

product:
<StringArray>
[        'Yoga Mat',           'Cereal',     'Fiction Book',
        'Sunscreen',           'Jacket',    'Mixer Grinder',
           'Coffee',       'Makeup Kit',     'Cookware Set',
            'Jeans',        'Face Wash',           'Snacks',
        'Olive Oil',         'Backpack',   'Self Help Book',
       'Smartphone',             'Rice',          'Monitor',
         'Sneakers',           'Laptop',       'Smartwatch',
       'Remote Car',         'Bedsheet',    'Running Shoes',
        'Dumbbells',   'Technical Book', 'Resistance Bands',
       'Headphones',   'Vacuum Cleaner',      'Cricket Bat',
          'Perfume',    'Business Book',       'Exam Guide',
    'Action Figure',          'Shampoo',          'T-Shirt',
        'Air Fryer',       'Board Game',           'Puzzle',
  'Educational Kit']
Length: 40, dtype: str

quantity:
[2 4 1 3 5 0]

unit_price:
[1064.49  481.5  1240.42 ... 3266.89 1680.23 3263.97]

discount_pct:
[0.15 0.05 0.   0.1  0.2  0.25 0.3  1.2  0.75 0.55]

discount_amount:
[319.35  96.3    0.   ... 490.03 168.02 652.79]

coupon_code:
<StringArray>
['No Coupon', 'SAVE15', 'WELCOME10', 'FESTIVE20', 'BANK10', 'APP5']
Length: 6, dtype: str

gross_sales:
[2128.98 1926.   1240.42 ... 9800.67 3360.46 3263.97]

revenue:
[1809.63 1829.7  1240.42 ... 3192.44 2611.18 1031.4 ]

cost:
[1026.85 1584.41  909.39 ... 7438.26 2309.63 2255.94]

shipping_cost:
[220.31  57.63 103.9  ... 270.35 164.61 117.29]

profit:
[ 562.47  187.65  227.12 ... 1743.55  718.2   237.95]

profit_margin:
[ 0.3108  0.1026  0.1831 ...  0.0995 -0.9973 -0.0934]

payment_method:
<StringArray>
[     'Net Banking',              'UPI',           'Wallet',
      'Credit Card', 'Cash on Delivery',       'Debit Card',
              'EMI']
Length: 7, dtype: str

shipping_type:
<StringArray>
['Standard', 'Same Day', 'Express']
Length: 3, dtype: str

delivery_days:
[7.  4.5 1.  8.  6.  4.3 5.  4.  3.  4.6 2.  4.4 0. ]

order_status:
<StringArray>
['Delivered', 'Cancelled', 'Returned', 'Pending', 'Failed']
Length: 5, dtype: str

return_reason:
<StringArray>
[ 'Not Returned',    'Wrong Item', 'Quality Issue',  'Changed Mind',
 'Late Delivery',       'Damaged',      'Size/Fit']
Length: 7, dtype: str

customer_rating:
[ 5. nan  4.  2.  3.  1.]

support_tickets:
[1. 0. 2. 3. 4. 5.]

In [178]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_age', 'gender',
       'city', 'state', 'customer_segment', 'customer_type',
       'acquisition_channel', 'product_category', 'product', 'quantity',
       'unit_price', 'discount_pct', 'discount_amount', 'coupon_code',
       'gross_sales', 'revenue', 'cost', 'shipping_cost', 'profit',
       'profit_margin', 'payment_method', 'shipping_type', 'delivery_days',
       'order_status', 'return_reason', 'customer_rating', 'support_tickets'],
      dtype='str')

In [200]:
df.describe()

,customer_age,quantity,unit_price,discount_pct,discount_amount,gross_sales,revenue,cost,shipping_cost,profit,profit_margin,delivery_days,customer_rating,support_tickets
count,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,11220.000000,15026.000000
mean,41.063157,1.735791,5906.695129,0.101015,1062.918167,10417.415837,9354.415144,6684.698551,167.043487,2502.755737,0.160843,4.451284,3.928342,0.597764
std,13.491628,1.019840,12934.722951,0.084807,3675.462591,27154.365348,24538.953739,17674.707454,82.434371,7467.267308,0.194072,1.996843,1.092495,0.773646
min,18.000000,0.000000,161.060000,0.000000,0.000000,161.060000,144.950000,92.210000,35.020000,-414.010000,-2.524100,0.000000,1.000000,0.000000
25%,29.000000,1.000000,786.212500,0.050000,23.787500,1097.312500,987.667500,706.255000,101.110000,102.840000,0.090600,3.000000,3.000000,0.000000
50%,41.000000,1.000000,1754.150000,0.100000,172.500000,2622.870000,2326.360000,1652.780000,161.355000,457.640000,0.188300,4.500000,4.000000,0.000000
75%,53.000000,2.000000,3771.000000,0.150000,584.132500,6623.887500,5885.175000,4200.887500,219.860000,1484.150000,0.288000,6.000000,5.000000,1.000000
max,64.000000,5.000000,85308.030000,1.200000,80593.660000,342840.300000,341232.120000,265728.540000,449.640000,133312.030000,0.448200,8.000000,5.000000,5.000000

In [188]:
df = df[df['customer_age'] <= 90]

In [190]:
df[df['customer_age'] > 90]

Empty DataFrame
Columns: [order_id, order_date, customer_id, customer_age, gender, city, state, customer_segment, customer_type, acquisition_channel, product_category, product, quantity, unit_price, discount_pct, discount_amount, coupon_code, gross_sales, revenue, cost, shipping_cost, profit, profit_margin, payment_method, shipping_type, delivery_days, order_status, return_reason, customer_rating, support_tickets]
Index: []

In [192]:
df['quantity'] = df['quantity'].abs()

In [195]:
(df['quantity'] < 0 ).sum()

np.int64(0)

In [196]:
df['delivery_days'] = df['delivery_days'].abs()

In [1]:
(df['delivery_days'] < 0 ).sum()

NameError: name 'df' is not defined

In [202]:
df['delivery_days'] = df['delivery_days'].round(1)

In [204]:
df['order_date'] = pd.to_datetime(df['order_date'])

ValueError: time data "01-09-2025" doesn't match format "%Y-%m-%d". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [205]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%d-%m-%Y')

ValueError: time data "2024-03-06" doesn't match format "%d-%m-%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [2]:
df.to_csv('sales_data_cleaned.csv', index=False)

NameError: name 'df' is not defined

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('sales_data_cleaned.csv')

In [4]:
df.describe()

,customer_age,quantity,unit_price,discount_pct,discount_amount,gross_sales,revenue,cost,shipping_cost,profit,profit_margin,delivery_days,customer_rating,support_tickets
count,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,15026.000000,11220.000000,15026.000000
mean,41.063157,1.735791,5906.695129,0.101015,1062.918167,10417.415837,9354.415144,6684.698551,167.043487,2502.755737,0.160843,4.451284,3.928342,0.597764
std,13.491628,1.019840,12934.722951,0.084807,3675.462591,27154.365348,24538.953739,17674.707454,82.434371,7467.267308,0.194072,1.996843,1.092495,0.773646
min,18.000000,0.000000,161.060000,0.000000,0.000000,161.060000,144.950000,92.210000,35.020000,-414.010000,-2.524100,0.000000,1.000000,0.000000
25%,29.000000,1.000000,786.212500,0.050000,23.787500,1097.312500,987.667500,706.255000,101.110000,102.840000,0.090600,3.000000,3.000000,0.000000
50%,41.000000,1.000000,1754.150000,0.100000,172.500000,2622.870000,2326.360000,1652.780000,161.355000,457.640000,0.188300,4.500000,4.000000,0.000000
75%,53.000000,2.000000,3771.000000,0.150000,584.132500,6623.887500,5885.175000,4200.887500,219.860000,1484.150000,0.288000,6.000000,5.000000,1.000000
max,64.000000,5.000000,85308.030000,1.200000,80593.660000,342840.300000,341232.120000,265728.540000,449.640000,133312.030000,0.448200,8.000000,5.000000,5.000000

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15026 entries, 0 to 15025
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              15026 non-null  str
 1   order_date            15026 non-null  datetime64[us]
 2   customer_id           15026 non-null  str
 3   customer_age          15026 non-null  float64
 4   gender                15026 non-null  str
 5   city                  15026 non-null  str
 6   state                 15026 non-null  str
 7   customer_segment      15026 non-null  str
 8   customer_type         15026 non-null  str
 9   acquisition_channel   15026 non-null  str
 10  product_category      15026 non-null  str
 11  product               15026 non-null  str
 12  quantity              15026 non-null  int64
 13  unit_price            15026 non-null  float64
 14  discount_pct          15026 non-null  float64
 15  discount_amount       15026 non-null  float64
 16  coupon_code           15026 non-null  str
 17  gross_sales           15026 non-null  float64
 18  revenue               15026 non-null  float64
 19  cost                  15026 non-null  float64
 20  shipping_cost         15026 non-null  float64
 21  profit                15026 non-null  float64
 22  profit_margin         15026 non-null  float64
 23  payment_method        15026 non-null  str
 24  shipping_type         15026 non-null  str
 25  delivery_days         15026 non-null  float64
 26  order_status          15026 non-null  str
 27  return_reason         15026 non-null  str
 28  customer_rating       11220 non-null  float64
 29  support_tickets       15026 non-null  float64
 30  order_month           15026 non-null  str
 31  order_year            15026 non-null  int32
 32  delivery_performance  15026 non-null  category
 33  discount_category     15026 non-null  category
dtypes: category(2), datetime64[us](1), float64(13), int32(1), int64(1), str(16)
memory usage: 3.6 MB

In [9]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True)

In [10]:
df['profit_margin'] = (df['profit'] / df['revenue']) * 100

In [11]:
df['order_month'] = df['order_date'].dt.to_period('M').astype(str)

In [13]:
df['order_year'] = df['order_date'].dt.year

In [14]:
df['delivery_performance'] = pd.cut(
    df['delivery_days'],
    bins=[-1, 2, 5, float('inf')],
    labels=['Fast', 'Normal', 'Delayed']
)

In [15]:
df['discount_category'] = pd.cut(
    df['discount_pct'],
    bins = [-1,10,25,50,float('inf')],
    labels = ['Low','Medium','High','Ver High']
)

In [17]:
df.to_csv('sales_data_cleaned1.csv', index=False)